=== Daniil0Yehorov/itroi/src/main/resources/static/xml/Full.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Product -->
    <xs:complexType name="Product">
        <xs:sequence>
            <xs:element name="ID" type="xs:integer" minOccurs="1"/>
            <xs:element name="Name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Description" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="500"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Price">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0.0"/>
                        <xs:fractionDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Category">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="CountInStock">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Products -->
    <xs:element name="Products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Product" maxOccurs="unbounded" type="Product"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Cart -->
    <xs:complexType name="CartType">
        <xs:sequence>
            <xs:element name="ID" type="xs:integer" minOccurs="1"/>
            <xs:element name="UserID" type="xs:integer" minOccurs="1"/>
            <xs:element name="ProductIDs">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ProductID" type="xs:integer" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="TotalAmount">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0.0"/>
                        <xs:fractionDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Carts -->
    <xs:element name="Carts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Cart" maxOccurs="unbounded" type="CartType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- User -->
    <xs:complexType name="UserType">
        <xs:sequence>
            <xs:element name="ID" type="xs:integer" minOccurs="1"/>
            <xs:element name="Type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="User"/>
                        <xs:enumeration value="Admin"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Login">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="5"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Password">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="8"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Phone" type="PhoneType" minOccurs="0"/>
            <xs:element name="Email" type="EmailType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Users -->
    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="User" maxOccurs="unbounded" type="UserType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- All Data -->
    <xs:element name="StoreData">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Products"/>
                <xs:element ref="Carts"/>
                <xs:element ref="Users"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Регулярні вирази -->
    <xs:simpleType name="PhoneType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+\d{1,3}-\d{1,4}-\d{6,10}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EmailType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".+@.+\..+"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Daniil0Yehorov/itroi/src/main/resources/static/xml/Full.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="test20.xslt"?>
<StoreData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Full.xsd">

    <!--Products -->
    <Products>
        <Product>
            <ID>1</ID>
            <Name>Whiskas Cat Food</Name>
            <Description>Сухий корм для котів зі смаком курки.</Description>
            <Price>50.00</Price>
            <Category>Корм для котів</Category>
            <CountInStock>901</CountInStock>
        </Product>
        <Product>
            <ID>2</ID>
            <Name>Pedigree Dog Food</Name>
            <Description>Сухий корм для собак зі смаком яловичини</Description>
            <Price>80.00</Price>
            <Category>Корм для собак</Category>
            <CountInStock>51</CountInStock>
        </Product>
    </Products>

    <!--Carts -->
    <Carts>
        <Cart>
            <UserID>1</UserID>
            <ProductIDs>
                <ProductID>1</ProductID>
                <ProductID>2</ProductID>
            </ProductIDs>
            <TotalAmount>130.00</TotalAmount>
            <status>Оформленний кошик</status>
        </Cart>
    </Carts>

    <!-- Users -->
    <Users>
        <User>
            <ID>1</ID>
            <Type>User</Type>
            <Login>DAnchik232</Login>
            <Password>BBeight23Ada</Password>
            <Name>Joe</Name>
            <Phone>+12-345-678901</Phone>
        </User>
        <User>
            <ID>2</ID>
            <Type>Admin</Type>
            <Login>AK232AKdadk2AD</Login>
            <Password>aldkakdLKADKL23</Password>
            <Name>Malfrey</Name>
            <Email>malfrey@example.com</Email>
        </User>
    </Users>

</StoreData>
