=== Daniil0Yehorov/itroi/src/main/resources/static/xml/koshik.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Carts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Cart" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:integer"/>
                            <xs:element name="UserID" type="xs:integer"/>
                            <xs:element name="Products">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ProductID" type="xs:integer" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="TotalAmount" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Daniil0Yehorov/itroi/src/main/resources/static/xml/koshik.xml
<?xml version="1.0" encoding="UTF-8"?>
<Carts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="koshik.xsd">
    <Cart>
        <ID>1</ID>
        <UserID>1</UserID>
        <Products>
            <ProductID>1</ProductID>
            <ProductID>2</ProductID>
        </Products>
        <TotalAmount>130.00</TotalAmount>
        <!--адрес куда вести-->
    </Cart>
</Carts>
