=== Daniil0Yehorov/itroi/src/main/resources/static/xml/User.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="User" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:integer"/>
                            <xs:element name="Type" type="xs:string"/>
                            <xs:element name="Login" type="xs:string"/>
                            <xs:element name="Password" type="xs:string"/>
                            <xs:element name="Name" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Daniil0Yehorov/itroi/src/main/resources/static/xml/User.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="User.xsd">
    <User>
        <ID>1</ID>
        <Type>User</Type>
        <Login>DAnchik232</Login>
        <Password>BBeight23Ada</Password>
        <Name>Joe</Name>
    </User>
    <User>
        <ID>2</ID>
        <Type>Admin</Type>
        <Login>AK232AKdadk2AD</Login>
        <Password>aldkakdLKADKL23</Password>
        <Name>Malfrey</Name>
    </User>
</Users>
